// src/views/Upload/components/UploadList.tsx
import classNames from 'classnames';
import React from 'react';

import { IFile } from '../types';
import style from './UploadList.module.scss';

interface IProps {
  fileList: IFile[];
  onCancelAll(): void;
  onStartAll(): void;
}

function UploadList({ fileList, onCancelAll, onStartAll }: IProps) {
  const cancelAll = () => {
    onCancelAll();
  };
  const startAll = () => {
    onStartAll();
  };
  return (
    <div>
      { !!fileList.length && (
        <div className={style.uploadActions}>
          <button className={style.actionButton} type="button" onClick={startAll}>全部开始</button>
          <button className={classNames(style.actionButton, style.redBtn)} type="button" onClick={cancelAll}>全部取消</button>
        </div>
      )}
      <ul className={style.uploadList}>
        {fileList.map((file) => (
          <li key={file.name} className={style.uploadFile}>
            <div className={style.fileContainer}>
              <div className={style.fileContent}>
                <p className={style.fineName}>{ file.name }</p>
                <p className={style.fileDesc}>
                  <span>{ file.process }%</span>
                  {/* <span v-if="file.process < 100">大约还需 -- 秒</span> */}
                </p>
              </div>
              <div>
                <i className={classNames(style.icon, style.iconClose, 'ri-close-line')} />
              </div>
            </div>
            <div className={style.fileProcess}>
              <div className={style.process} style={{ width: `${file.process}%` }} />
            </div>
          </li>
        ))}
      </ul>
    </div>
  );
}

export default UploadList;

// src/pages/upload/components/UploadList.vue
<script setup lang="ts">
import { inject } from '@vue/runtime-core';
import { FileKey } from '../symbols';

const fileList = inject(FileKey);

interface IEmit {
  (event: 'startAll'): void;
  (event: 'cancelAll'): void;
}
const emit = defineEmits<IEmit>();

const cancelAll = () => {
  emit('cancelAll');
};
const startAll = () => {
  emit('startAll');
};

</script>

<template>
  <div v-show="fileList?.length" class="upload-actions">
    <button class="button gradient" @click="startAll">全部开始</button>
    <button class="button gradient red" @click="cancelAll">全部取消</button>
  </div>
  <ul class="upload-list">
    <li v-for="(file, idx) in fileList" :key="idx" class="upload-file">
      <div class="file-container">
        <div class="file-content">
          <p class="file-name">{{ file.name }}</p>
          <p class="file-desc">
            <span>{{ file.process }}%</span>
            <!-- <span v-if="file.process < 100">大约还需 -- 秒</span> -->
          </p>
        </div>
        <div class="file-action">
          <i class="icon close ri-close-line"></i>
        </div>
      </div>
      <div class="file-process">
        <div class="process" :style="{width: file.process + '%'}"></div>
      </div>
    </li>
  </ul>
</template>

<style lang="scss">
@import './uploadList.scss';
</style>
